name: pep8formatting
on:
  pull_request:
    branches: [ main ]
jobs:
  autopep8:
    # Check if the PR is not raised by this workflow and is not from a fork
    if: startsWith(github.head_ref, 'autopep8-patches') == false && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install code formatting tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install autopep8 autoflake isort
      - name: autoflakecheck
        id: autoflakecheck
        continue-on-error: true
        run: |
          autoflake --remove-all-unused-imports --recursive --in-place --check .
      - name: autoflake
        id: autoflake
        run: |
          autoflake --remove-all-unused-imports --recursive --in-place .
      - name: autopep8
        id: autopep8
        continue-on-error: true
        run: |
          autopep8 --max-line-length 127 --recursive --in-place --exit-code .
      - name: isortcheck
        id: isortcheck
        continue-on-error: true
        run: |
          isort --line-length 127 --check .
      - name: isort-fix
        id: isortfix
        run: |
          isort --line-length 127 .
      - name: Create Pull Request
        if: steps.autopep8.outcome == 'failure' || steps.autoflakecheck.outcome == 'failure' || steps.isortcheck.outcome == 'failure'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: pep8formatting action fixes
          title: Fixes by autopep8 action
          body: This is an auto-generated PR with fixes by autopep8 and autoflake.
          labels: autopep8, automated pr
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outcome == 'failure' || steps.autoflakecheck.outcome == 'failure' || steps.isortcheck.outcome == 'failure'
        run: exit 1
